#!/usr/bin/env python3
"""Reduce the open review backlog to the decisions it actually contains.

The atlas records 726 review items. 178 of them were required and all 178 are resolved, so
nothing outstanding blocks a release; the remaining 548 are confirmations the pipeline asked for
after making a defensible choice of its own.

Read one at a time that is 542 open items. Grouped by what is actually being asked, they collapse
to a handful of questions, each repeated across tens or hundreds of structures. This writes the
sheet that says which ones, what the pipeline does about each today, how many structures each
covers, and how many observations each withholds — which is the part worth spending effort on.

Nothing here decides anything. The decision column is empty and is meant to stay that way until
a person writes in it.

    python3 pipeline/validation/build_review_decision_sheet.py
"""
from __future__ import annotations

import collections
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
UNIVERSE = ROOT / "data/intermediate/phase4/canonical_review_universe.jsonl"
RESOLVED = ROOT / "config/phase5/resolved_review_items.json"
SHEET = ROOT / "curation/review_decisions.csv"
REPORT = ROOT / "reports/validation/REVIEW_DECISIONS.md"
EXAMPLES = 5

# What each group is asking, in the terms the pipeline itself uses. The effect is read from the
# records, never assumed; only the phrasing of the question is written here.
QUESTIONS = {
    "mutation_mapping_unresolved":
        "The deposited construct cannot be compared with the reference sequence at some "
        "positions, because the reference residue identity is not available there. Whether "
        "those positions carry a mutation is therefore unknown, not absent.",
    "source_conflict:annotated_component_absent":
        "The annotation names a chemical component that is not present in the deposited "
        "coordinates. The two sources disagree and both are currently kept.",
    "annotated_not_observed":
        "A ligand is annotated for the structure but was not found in the coordinates, so it "
        "has no contacts and no binding site to classify.",
    "aminergic_regression_discrepancy":
        "The generic positions computed for this structure differ from the frozen aminergic "
        "reference.",
    "receptor_mapping":
        "No polymer entity in the deposition carried the receptor accession GPCRdb lists.",
}


def main() -> int:
    rows = [json.loads(line) for line in UNIVERSE.read_text(encoding="utf-8").splitlines() if line.strip()]
    resolved = set(json.loads(RESOLVED.read_text(encoding="utf-8"))["review_item_ids"])
    open_rows = [r for r in rows if r["review_item_id"] not in resolved]

    grouped = collections.defaultdict(list)
    for row in open_rows:
        grouped[tuple(sorted(row.get("issue_types") or []))].append(row)

    records = []
    for issues, members in sorted(grouped.items(), key=lambda kv: -len(kv[1])):
        # The question is named by the issue that carries the decision; the others travel with it.
        primary = next((i for i in issues if i in QUESTIONS), issues[0] if issues else "")
        eligibility = collections.Counter(str(m.get("current_eligibility")) for m in members)
        proposals = collections.Counter(str(m.get("automated_proposal")) for m in members)
        excluded = sum(n for k, n in eligibility.items() if k.startswith("excluded"))
        records.append({
            "group": " + ".join(issues),
            "question": QUESTIONS.get(primary, ""),
            "items": len(members),
            "structures": len({m["pdb_id"] for m in members}),
            "observations_currently_excluded": excluded,
            "pipeline_does_now": "; ".join(f"{k} ({n})" for k, n in proposals.most_common(2)),
            "current_eligibility": "; ".join(f"{k} ({n})" for k, n in eligibility.most_common(3)),
            "example_pdb_ids": " ".join(sorted({m["pdb_id"] for m in members})[:EXAMPLES]),
            "decision": "",
            "decided_by": "",
            "decided_on": "",
            "notes": "",
        })

    SHEET.parent.mkdir(parents=True, exist_ok=True)
    with SHEET.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(records[0]))
        writer.writeheader()
        writer.writerows(records)

    required = [r for r in rows if r["human_review_requirement"] == "required"]
    lines = [
        "# Review decisions outstanding",
        "",
        "Generated by `pipeline/validation/build_review_decision_sheet.py`.",
        "",
        f"The atlas records {len(rows)} review items. {len(required)} were required and "
        f"{sum(1 for r in required if r['review_item_id'] in resolved)} of those are resolved, so "
        "nothing outstanding blocks a release. The rest are confirmations, and they are the same "
        "few questions repeated:",
        "",
        f"**{len(open_rows)} open items — {len(records)} questions.**",
        "",
        f"Of those {len(open_rows)} items, "
        f"{sum(r['observations_currently_excluded'] for r in records)} withhold an observation "
        "from the atlas today. The rest record an uncertainty that changes no number and no "
        "count: deciding them would close the item without moving anything a reader sees. That "
        "is where the effort is worth spending, and where it is not.",
        "",
        "| Question | Items | Structures | Observations excluded today |",
        "|---|---:|---:|---:|",
    ]
    for record in records:
        lines.append(f"| {record['group']} | {record['items']} | {record['structures']} |"
                     f" {record['observations_currently_excluded']} |")
    lines += ["", "## What each one asks", ""]
    for record in records:
        lines += [f"### {record['group']}", "",
                  record["question"] or "_No standing description; read the records._", "",
                  f"- **{record['items']} items across {record['structures']} structures.**",
                  f"- Pipeline today: {record['pipeline_does_now']}",
                  f"- Current eligibility: {record['current_eligibility']}",
                  f"- Examples: {record['example_pdb_ids']}", ""]
    lines += [
        f"Sheet: `{SHEET.relative_to(ROOT)}`. The `decision` column is empty and nothing in this",
        "pipeline fills it. A decision recorded there applies to every item in its group; that is",
        "the point of grouping them, and it is also the reason a decision must be written as a",
        "rule rather than as a verdict on one structure.",
        "",
    ]
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"open_items": len(open_rows), "questions": len(records),
                      "sheet": str(SHEET.relative_to(ROOT)),
                      "report": str(REPORT.relative_to(ROOT))}, indent=1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
